### ISSUE TITLE
Terminus freezes when running more than 30 lines in R

### ISSUE THREAD

**Issue by albertostefanelli** [randy3k/Terminus#41] opened 2018-08-27 21:41 UTC
This happens with Sublime Text 3 (Build 3176) when copying the code in the Terminus panel and view or using SendCode. I report the R session hereunder even if I don't believe R is causing the problem since if i use SendCode with R-Gui or R-Studio this problem does not appear 

> sessionInfo()                             
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by randy3k** [comment] 2018-08-27 22:15
Thanks. I could reproduce it. 


My commendation is to switch to [rtichoke](https://github.com/randy3k/rtichoke) because it has better support of bracketed paste mode.

If you are using SendCode, you will need to turn on bracketed paste mode via the settings.

**Comment by randy3k** [comment] 2018-08-27 22:21
It seems to be caused by `readline` which has a reading limit of 1024 bytes.

**Comment by randy3k** [comment] 2018-08-27 22:43
fixed by cb7a7f5

**Closed by randy3k** 2018-08-27 22:43 UTC
