### ISSUE TITLE
Terminus hangs when executing the reset command

### ISSUE THREAD

**Issue by campeon91** [randy3k/Terminus#96] opened 2019-03-13 21:52 UTC
When i try to clear my terminal using the `reset` command, Terminus hangs and i'm not able to write anything inside the terminal's panel.

Steps to reproduce:
- open a terminus panel.
- execute `reset` command.
- check if the terminal is still usable

**Comment by randy3k** [comment] 2019-03-13 23:21
What OS and shell are you using? It is definitely working on my macOS's zsh.

**Comment by randy3k** [comment] 2019-03-16 19:56
I was able to reproduce on a debian machine. It was caused by wrong OSC pattern detection. It should be now fixed. A release will be published soon.

**Closed by randy3k** 2019-03-16 19:56 UTC
